p8105_hw6_ez2384
================

``` r
  library(p8105.datasets)
  library(tidyverse)
  library(dplyr)
  library(readr)
  library(modelr)
  library(patchwork)
```

### Problem 1

##### Extract Data

``` r
  weather_df = 
    rnoaa::meteo_pull_monitors(
      c("USW00094728"),
      var = c("PRCP", "TMIN", "TMAX"), 
      date_min = "2017-01-01",
      date_max = "2017-12-31") %>%
    mutate(
      name = recode(id, USW00094728 = "CentralPark_NY"),
      tmin = tmin / 10,
      tmax = tmax / 10) %>%
    select(name, id, everything())
```

##### Generate 5000 Bootstrap Samples, obtain R2 and log quantities

- Function of `tmax` against `tmin`.
- Produces estimates of R^2 and log quantities per bootstrap sample.

``` r
  bootstrap_samples = weather_df %>% modelr::bootstrap(n = 5000)
  bootstrap_results = bootstrap_samples %>% 
                      mutate(
                        models    = map(.x=strap, .f=~lm(tmax~tmin, data=.x)),
                        r_squared = map_dbl(.x=models, .f=~broom::glance(.x)$r.squared),
                        log_betas = map_dbl(.x=models, .f=~log(coef(.x)[1]*coef(.x)[2]))
                      )
```

##### Plot of estimate distributions and remark

``` r
  R2_plot = bootstrap_results %>%
            ggplot(aes(x=r_squared)) +
              geom_histogram(bins=100, fill="blue", alpha=.75, color="black", size=.25) +
              labs(
                title = "Distribution of R^2 Estimates",
                    x = "R^2 Estimates",
                    y = "Frequency"
              ) +
              xlim(.85,1)+
              ylim(0,500)+
              theme_light()+
              theme(plot.title = element_text(hjust=.5))
  
  Log_plot = bootstrap_results %>%
             ggplot(aes(x=log_betas)) +
             geom_histogram(bins=100, fill="darkgreen", alpha=.75, color="black", size=.25) +
             labs(
                  title = "Distribution of log(β0*β1) Estimates",
                      x = "log(β0*β1) Estimates",
                      y = "Frequency"
                 ) +
             theme_light()+
             theme(plot.title = element_text(hjust=.5))
  
  R2_plot / Log_plot
```

![](p8105_hw6_ez2384_files/figure-gfm/p1%20Distribution%20Plots-1.png)<!-- -->

- R2_plot: A unimodal, slightly symmetric distribution of R2 values
  centered around 0.92, indicating high model performance across
  bootstrap samples. This reflects that the linear model `tmax∼tmin`
  consistently explains a high proportion of the variance in tmax
  (maximum temperature) across bootstrap samples. The plot reflects a
  statistical robust linear relationship of `tmax∼tmin`.
- log(ß0\*ß1)\_plot: The histogram displays a slightly right-skewed
  distribution of values, concentrated between 1.90 and 2.10, with most
  falling near 2.00. This indicates that the product of the intercept ß0
  and slope ß1 in the regression model has a consistent logarithmic
  value, with minor variations across bootstrap samples. The plot
  indicates a predictable interaction between the intercept and slope,
  with only minor variations in their combined influence.

##### Upper & Lower Quantiles

``` r
  quantile(bootstrap_results$r_squared, probs = c(.025, .975)) %>% 
    tibble(
            `95% CI bounds for R2` = c("lower bound", "upper bound"),
                Value = round(., 4)
          ) %>% 
  select(`95% CI bounds for R2`, Value) %>% 
  knitr::kable()
```

| 95% CI bounds for R2 |  Value |
|:---------------------|-------:|
| lower bound          | 0.8942 |
| upper bound          | 0.9270 |

``` r
  quantile(bootstrap_results$log_betas, probs = c(.025, .975)) %>% 
    tibble(
            `95% CI bounds for log(ß0*ß1)` = c("lower bound", "upper bound"),
                Value = round(., 4)
          ) %>% 
  select(`95% CI bounds for log(ß0*ß1)`, Value) %>% 
  knitr::kable()
```

| 95% CI bounds for log(ß0\*ß1) |  Value |
|:------------------------------|-------:|
| lower bound                   | 1.9667 |
| upper bound                   | 2.0603 |

### Problem 2

##### Preparation and Mutation of Dataset

- Create variable `city_state` as instructed, and create variable
  `indicator` to indicate whether the homicide has been resolved.
- Cities `Dallas, TX`, `Phoenix, AZ`, `Kansas City, MO`, `Tulsa, AL` has
  been omitted.
- Per instruction, `victim_age` has been turned to numeric type from
  chr, with non-numeric cell values converted into `NA`.

``` r
  homicide_data = read.csv("../../Datasets/homicide_data.csv") %>%
                  mutate(
                    city_state = paste(city, state, sep=", "),
                     indicator = ifelse(disposition=="Closed by arrest", 1, 0)
                  ) %>% 
                  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")) %>% 
                  filter(victim_race %in% c("Black", "White")) %>% 
                  mutate(
                    victim_age = ifelse(grepl("[^0-9]", victim_age), NA, victim_age),
                    victim_age = as.numeric(victim_age)
                  )
```

- Creates and Stores a Logistic Regression Model, Extract OR and
  confidence intervals for `Baltimore, MD`.

``` r
  baltimore_model = glm(
                      indicator ~ victim_age + victim_sex + victim_race,
                           data = homicide_data %>% filter(city_state == "Baltimore, MD"),
                         family = "binomial"
                    )
  baltimore_model  
```

    ## 
    ## Call:  glm(formula = indicator ~ victim_age + victim_sex + victim_race, 
    ##     family = "binomial", data = homicide_data %>% filter(city_state == 
    ##         "Baltimore, MD"))
    ## 
    ## Coefficients:
    ##      (Intercept)        victim_age    victim_sexMale  victim_raceWhite  
    ##         0.309981         -0.006727         -0.854463          0.841756  
    ## 
    ## Degrees of Freedom: 2752 Total (i.e. Null);  2749 Residual
    ## Null Deviance:       3568 
    ## Residual Deviance: 3493  AIC: 3501

``` r
  baltimore_summary = broom::tidy(baltimore_model, conf.int = TRUE, exp = TRUE)
  
  baltimore_summary %>%
    filter(term == "victim_sexMale") %>%
    select(term, estimate, conf.low, conf.high)
```

    ## # A tibble: 1 × 4
    ##   term           estimate conf.low conf.high
    ##   <chr>             <dbl>    <dbl>     <dbl>
    ## 1 victim_sexMale    0.426    0.324     0.558

- Repeat for each cities in the dataset.

``` r
  city_results = homicide_data %>%
                 group_by(city_state) %>%
                 nest() %>%
                 mutate(
                        model = map(.x=data, .f= ~ glm( 
                                                      indicator ~ victim_age + victim_sex + victim_race,
                                                      family = "binomial",
                                                        data = .x
                                                   )
                                ),
                         tidy_model = map(.x=model, .f= ~ broom::tidy(.x, conf.int = TRUE, exp = TRUE)),
                        sex_results = map(.x=tidy_model, .f= ~ filter(.x, term == "victim_sexMale"))
                 ) %>%
                 select(city_state, sex_results) %>%
                 unnest(sex_results)
```

- Create the Plot.

``` r
  ggplot(data=city_results, mapping=aes(x = reorder(city_state, estimate), y = estimate)) +
    geom_point(size=.8) +
    geom_errorbar(mapping=aes(ymin = conf.low, ymax = conf.high), width = .2, size=.4) +
    coord_flip() +
    labs(
      title = "Adjusted Odds Ratios & CI for Solving Homicides comparing Male with Female Victims",
      x = "City",
      y = "Adjusted Odds Ratios comparing Male vs, Female"
    ) +
    theme_light()+
    theme( plot.title = element_text(hjust=.5), )
```

![](p8105_hw6_ez2384_files/figure-gfm/p2%20Plot-1.png)<!-- -->

##### Remarks on Plot

- The plot highlights a pervasive trend across most cities where
  homicides involving male victims are less likely to be solved compared
  to female victims. This is evident as the majority of the odds ratios
  for solving homicides for male victims compared to female victims are
  below 1, indicating that male victims are generally less likely to
  have their cases solved than female victims.

- While this finding applies to many cities and is supported by
  confidence intervals that exclude 1, there are several cities, such as
  `Las Vegas, NV`, and `San Bernardino, CA`, where the 95% confidence
  intervals overlap with 1. This overlap suggests that the observed
  difference in solving rates for male and female victims may not be
  statistically significant in these cities.

- Cities like `Albuquerque, NM`, `Stockton, CA`, and `Fresno, CA`
  exhibit very wide confidence intervals that overlap with 1, indicating
  high uncertainty in the estimates for these cities.

- A few cities, such as `San Francisco, CA`, and `New Orleans, LA`, have
  odds ratios close to 1 with confidence intervals overlapping 1. This
  suggests no significant difference in solving rates for male versus
  female victims in these cities.

### Problem 3

``` r
  birthweight_data = read.csv(file="../../Datasets/birthweight.csv") %>% 
                     mutate(
                        babysex = factor(babysex, labels = c("Male", "Female")),
                          frace = factor(frace),
                        malform = factor(malform, labels = c("Absent", "Present")),
                          mrace = factor(mrace)
                     ) %>% 
                     drop_na()
```

``` r
  full_model = lm(
                  bwt ~ blength + bhead + gaweeks + wtgain + fincome + mheight + parity + babysex + mrace + frace + malform, 
                  data = birthweight_data
               )
  summary(full_model)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ blength + bhead + gaweeks + wtgain + fincome + 
    ##     mheight + parity + babysex + mrace + frace + malform, data = birthweight_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1109.46  -184.86    -5.49   179.25  2463.91 
    ## 
    ## Coefficients:
    ##                  Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)    -6.384e+03  1.351e+02 -47.262  < 2e-16 ***
    ## blength         7.707e+01  2.033e+00  37.903  < 2e-16 ***
    ## bhead           1.341e+02  3.472e+00  38.623  < 2e-16 ***
    ## gaweeks         1.113e+01  1.478e+00   7.527 6.28e-14 ***
    ## wtgain          3.626e+00  3.929e-01   9.230  < 2e-16 ***
    ## fincome         3.671e-01  1.772e-01   2.072 0.038307 *  
    ## mheight         1.031e+01  1.650e+00   6.251 4.49e-10 ***
    ## parity          9.729e+01  4.082e+01   2.384 0.017182 *  
    ## babysexFemale   3.250e+01  8.547e+00   3.803 0.000145 ***
    ## mrace2         -1.444e+02  4.646e+01  -3.107 0.001901 ** 
    ## mrace3         -1.029e+02  7.245e+01  -1.420 0.155728    
    ## mrace4         -6.330e+01  4.561e+01  -1.388 0.165324    
    ## frace2          3.165e+01  4.658e+01   0.679 0.496896    
    ## frace3          3.643e+01  7.003e+01   0.520 0.602970    
    ## frace4         -2.369e+01  4.509e+01  -0.525 0.599410    
    ## frace8          1.418e+00  7.487e+01   0.019 0.984887    
    ## malformPresent  8.675e-03  7.139e+01   0.000 0.999903    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 275.6 on 4325 degrees of freedom
    ## Multiple R-squared:  0.7115, Adjusted R-squared:  0.7105 
    ## F-statistic: 666.8 on 16 and 4325 DF,  p-value: < 2.2e-16

``` r
  backward_model = MASS::stepAIC(full_model, direction = "backward")
```

    ## Start:  AIC=48811.14
    ## bwt ~ blength + bhead + gaweeks + wtgain + fincome + mheight + 
    ##     parity + babysex + mrace + frace + malform
    ## 
    ##           Df Sum of Sq       RSS   AIC
    ## - frace    4     99717 328546657 48804
    ## - malform  1         0 328446940 48809
    ## <none>                 328446940 48811
    ## - fincome  1    326089 328773028 48813
    ## - parity   1    431502 328878441 48815
    ## - mrace    3    835415 329282355 48816
    ## - babysex  1   1098121 329545060 48824
    ## - mheight  1   2966947 331413886 48848
    ## - gaweeks  1   4302555 332749494 48866
    ## - wtgain   1   6469557 334916497 48894
    ## - blength  1 109101931 437548871 50054
    ## - bhead    1 113284511 441731451 50096
    ## 
    ## Step:  AIC=48804.46
    ## bwt ~ blength + bhead + gaweeks + wtgain + fincome + mheight + 
    ##     parity + babysex + mrace + malform
    ## 
    ##           Df Sum of Sq       RSS   AIC
    ## - malform  1         0 328546657 48802
    ## <none>                 328546657 48804
    ## - fincome  1    320229 328866886 48807
    ## - parity   1    431703 328978360 48808
    ## - babysex  1   1093140 329639797 48817
    ## - mheight  1   3000718 331547374 48842
    ## - gaweeks  1   4309194 332855851 48859
    ## - wtgain   1   6489458 335036115 48887
    ## - mrace    3  10599591 339146248 48936
    ## - blength  1 109063280 437609937 50047
    ## - bhead    1 113293152 441839809 50089
    ## 
    ## Step:  AIC=48802.46
    ## bwt ~ blength + bhead + gaweeks + wtgain + fincome + mheight + 
    ##     parity + babysex + mrace
    ## 
    ##           Df Sum of Sq       RSS   AIC
    ## <none>                 328546657 48802
    ## - fincome  1    320337 328866994 48805
    ## - parity   1    431708 328978365 48806
    ## - babysex  1   1093449 329640106 48815
    ## - mheight  1   3001071 331547728 48840
    ## - gaweeks  1   4309503 332856160 48857
    ## - wtgain   1   6496407 335043064 48885
    ## - mrace    3  10612479 339159136 48934
    ## - blength  1 109098023 437644680 50045
    ## - bhead    1 113297768 441844425 50087

``` r
  summary(backward_model)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ blength + bhead + gaweeks + wtgain + fincome + 
    ##     mheight + parity + babysex + mrace, data = birthweight_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1109.57  -184.82    -5.27   179.48  2462.49 
    ## 
    ## Coefficients:
    ##                 Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)   -6383.7556   134.9436 -47.307  < 2e-16 ***
    ## blength          77.0317     2.0315  37.919  < 2e-16 ***
    ## bhead           134.0760     3.4697  38.642  < 2e-16 ***
    ## gaweeks          11.1343     1.4774   7.536 5.85e-14 ***
    ## wtgain            3.6309     0.3924   9.253  < 2e-16 ***
    ## fincome           0.3630     0.1767   2.055 0.039968 *  
    ## mheight          10.3660     1.6483   6.289 3.51e-10 ***
    ## parity           97.3167    40.7987   2.385 0.017109 *  
    ## babysexFemale    32.4253     8.5416   3.796 0.000149 ***
    ## mrace2         -113.4372     9.6507 -11.754  < 2e-16 ***
    ## mrace3          -72.3384    42.5342  -1.701 0.089069 .  
    ## mrace4          -84.6149    19.4621  -4.348 1.41e-05 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 275.5 on 4330 degrees of freedom
    ## Multiple R-squared:  0.7115, Adjusted R-squared:  0.7107 
    ## F-statistic: 970.6 on 11 and 4330 DF,  p-value: < 2.2e-16

##### Remark on Building and Commentting on Reduced Model

- Initial Full Model includes all predictors.  
- Backward selection was applied using `stepAIC()` to remove predictors
  that did not significantly improve the model based on the AIC, which
  retains all statistically meaningful predictors and excludes all
  non-significant predictors to reduce complexity and enhance
  interpretability.  
- The Final Model includes the following predictors
  - continuous variables
    - `blength`, `bhead`, `gaweeks`, `wtgain`, `fincome`, `mheight`,
      `parity`  
  - categorical variables
    - `babysex`(ref=“Female”), `mrace`(ref=“1”)  
- The reduced model has an adjusted R^2 of 0.7107 which implies a pretty
  good fit and about 71% of the variance in the birthweight can be
  explained by the reduced model. The residual error of 275.5 grams
  suggests the typical deviation of observed birthweights from those
  predicted by the model is 275.5 grams.

``` r
  model_1 = lm(bwt ~ blength + gaweeks, data = birthweight_data)
  summary(model_1)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ blength + gaweeks, data = birthweight_data)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -1709.6  -215.4   -11.4   208.2  4188.8 
    ## 
    ## Coefficients:
    ##              Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) -4347.667     97.958  -44.38   <2e-16 ***
    ## blength       128.556      1.990   64.60   <2e-16 ***
    ## gaweeks        27.047      1.718   15.74   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 333.2 on 4339 degrees of freedom
    ## Multiple R-squared:  0.5769, Adjusted R-squared:  0.5767 
    ## F-statistic:  2958 on 2 and 4339 DF,  p-value: < 2.2e-16

``` r
  model_2 = lm(bwt ~ bhead*blength*babysex, data = birthweight_data)
  summary(model_2)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ bhead * blength * babysex, data = birthweight_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1132.99  -190.42   -10.33   178.63  2617.96 
    ## 
    ## Coefficients:
    ##                               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)                 -7176.8170  1264.8397  -5.674 1.49e-08 ***
    ## bhead                         181.7956    38.0542   4.777 1.84e-06 ***
    ## blength                       102.1269    26.2118   3.896 9.92e-05 ***
    ## babysexFemale                6374.8684  1677.7669   3.800 0.000147 ***
    ## bhead:blength                  -0.5536     0.7802  -0.710 0.478012    
    ## bhead:babysexFemale          -198.3932    51.0917  -3.883 0.000105 ***
    ## blength:babysexFemale        -123.7729    35.1185  -3.524 0.000429 ***
    ## bhead:blength:babysexFemale     3.8781     1.0566   3.670 0.000245 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 287.7 on 4334 degrees of freedom
    ## Multiple R-squared:  0.6849, Adjusted R-squared:  0.6844 
    ## F-statistic:  1346 on 7 and 4334 DF,  p-value: < 2.2e-16

``` r
  set.seed(1)
  cv_splits = crossv_mc(birthweight_data, n = 100) %>%
              mutate(
                train = map(train, as.data.frame),
                test = map(test, as.data.frame)
              )

  rmse = function(model, data) {
                                  if (is.null(data$bwt)) {
                                                            stop("bwt column missing in test data")
                                                          }
                                  preds = predict(model, newdata = data)
                                  sqrt(mean((data$bwt - preds)^2))
                                }
  
  cv_results = cv_splits %>%
               mutate(
                      backward = map(train, ~lm(bwt ~ blength+bhead+gaweeks+wtgain+fincome+mheight+parity+babysex+mrace, data = .x)),
                      model1 = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
                      model2 = map(train, ~lm(bwt ~ bhead * blength * babysex, data = .x)),
                      backward_rmse = map2_dbl(backward, test, rmse),
                      model1_rmse = map2_dbl(model1, test, rmse),
                      model2_rmse = map2_dbl(model2, test, rmse)
                    )
    
  cv_results %>% select(backward_rmse, model1_rmse, model2_rmse)
```

    ## # A tibble: 100 × 3
    ##    backward_rmse model1_rmse model2_rmse
    ##            <dbl>       <dbl>       <dbl>
    ##  1          283.        360.        302.
    ##  2          268.        322.        280.
    ##  3          266.        307.        279.
    ##  4          287.        337.        298.
    ##  5          290.        367.        303.
    ##  6          273.        314.        282.
    ##  7          277.        357.        290.
    ##  8          289.        346.        301.
    ##  9          273.        327.        287.
    ## 10          275.        338.        292.
    ## # ℹ 90 more rows

``` r
  birthweight_data = birthweight_data %>%
                      add_predictions(backward_model, var = "predicted_bwt") %>%
                      add_residuals(backward_model, var = "residuals")
  head(birthweight_data)
```

    ##   babysex bhead blength  bwt delwt fincome frace gaweeks malform menarche
    ## 1  Female    34      51 3629   177      35     1    39.9  Absent       13
    ## 2    Male    34      48 3062   156      65     2    25.9  Absent       14
    ## 3  Female    36      50 3345   148      85     1    39.9  Absent       12
    ## 4    Male    34      52 3062   157      55     1    40.0  Absent       14
    ## 5  Female    34      52 3374   156       5     1    41.6  Absent       13
    ## 6    Male    33      52 3374   129      55     1    40.7  Absent       12
    ##   mheight momage mrace parity pnumlbw pnumsga    ppbmi ppwt smoken wtgain
    ## 1      63     36     1      3       0       0 26.27184  148      0     29
    ## 2      65     25     2      0       0       0 21.34485  128      0     28
    ## 3      64     29     1      0       0       0 23.56517  137      1     11
    ## 4      64     18     1      0       0       0 21.84508  127     10     30
    ## 5      66     20     1      0       0       0 21.02642  130      1     26
    ## 6      66     23     1      0       0       0 18.60030  115      0     14
    ##   predicted_bwt  residuals
    ## 1      3643.145  -14.14476
    ## 2      2846.349  215.65077
    ## 3      3505.476 -160.47565
    ## 4      3418.172 -356.17209
    ## 5      3456.469  -82.46933
    ## 6      3254.527  119.47276

``` r
  ggplot(birthweight_data, aes(x = predicted_bwt, y = residuals)) +
    geom_point(size=.5) +
    geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
    labs(
      title = "Residuals vs. Fitted Values (Backward Selection Model)",
      x = "Fitted Values (Predicted Birthweight)",
      y = "Residuals"
    ) +
    theme_light() +
    theme( plot.title = element_text(hjust=.5), )
```

![](p8105_hw6_ez2384_files/figure-gfm/p3%20plots-1.png)<!-- -->

``` r
  cv_summary = cv_results %>%
               summarize(
                 backward_rmse = mean(backward_rmse),
                   model1_rmse = mean(model1_rmse),
                   model2_rmse = mean(model2_rmse)
               )

  cv_results_long <- cv_results %>%
                     pivot_longer(cols = c(backward_rmse, model1_rmse, model2_rmse), names_to = "model", values_to = "rmse")
  
  ggplot(data=cv_results_long, mapping=aes(x = model, y = rmse, fill=model)) +
    geom_violin() +
    stat_summary(fun = median, geom = "point", shape = 21, size = 1.5, fill = "white", color = "black") +
      stat_summary(fun = mean, geom = "point", shape = 23, size = 1.5, fill = "red", color = "black") +
    labs(
      title = "Cross-Validated RMSE for Each Model",
      x = "Model",
      y = "RMSE"
    ) +
    theme_light() +
    theme( plot.title = element_text(hjust=.5), )
```

![](p8105_hw6_ez2384_files/figure-gfm/p3%20plots-2.png)<!-- -->

##### Remark on RMSE across models

- The backward model (red) shows the smallest spread of RMSE values,
  indicating consistent performance across cross-validation splits. The
  first model (green) has the largest spread of RMSE values, suggesting
  greater variability in performance. The second model (blue) also shows
  a compact distribution similar to the backward model, though slightly
  more dispersed.  
- The backward model exhibits the lowest RMSE median and mean,
  demonstrating its superior predictive accuracy compared to the other
  models. The first model has the highest median and mean RMSE,
  indicating weaker predictive performance.  
- Overall, the backward selection model appears to be the best model
  overall, with both lower RMSE values and less variability.
